### ISSUE TITLE
[cancelled] set up SSO on the EA Wiki

### ISSUE THREAD

**Issue by tog22** [tog22/eahub#10]
Talk to Eric Bruylant ( elliotbrown2@gmail.com ) and Ozzie Gooen ( @OAGr )

**Comment by tog22** [comment]
@cdc482 _might_ have time to help

**Comment by OAGr** [comment]
From Eric:
I believe there's a module for this at http://drupal.org/project/modules . If you can't find one, the best places to search and ask are http://drupal.stackexchange.com and (less good) the drupal.org forums.

I'm making good progress on setting up the wiki (http://wiki.effectivealtruismhub.com/w/index.php?title=Effective_Altruism_Wiki), but there're a few things that need more than FTP. I've put them in the needs higher access section of https://impact.hackpad.com/EA-Hub-WIki-UTBbe0xYQZD

Note that we want OAuth 1.0a not OAuth2, to work with http://www.mediawiki.org/wiki/Extension:OAuthAuthentication (in place ofhttp://www.mediawiki.org/wiki/Extension:OAuth)

Getting SSO done asap would be a big plus since it'd let other people make accounts on the wiki without adding extra complication when we switch over. I'm around most of the time between now and the 13th, except weekends, and this is my primary project.

**Comment by tog22** [comment]
@cdc482 can you list the possible modules?

**Comment by arichard4** [comment]
Incidentally, one other possible solution would be to use the wiki attached to the EA forum, since you could then reuse the accounts from the forum. (I believe LW does this; I'm not sure how difficult this would be, so it might be worth asking whoever implemented it for LW.)

**Comment by tog22** [comment]
Cancelled
