### ISSUE TITLE
"Edit donations" page contains references to 2013

### ISSUE THREAD

**Issue by mwerbos** [tog22/eahub#15]
For some reason the edit page for a user's donations still prompts them with "Lifetime amount donated through 2013", "Charities donated to in 2013", "Pre-tax income in 2013", and "Amount donated in 2013".

Perhaps this could be updated to some kind of $LAST_YEAR expression, since I'm guessing it's just a manually-entered string right now? Though that might require some way of archiving or labeling past answers based on when they were entered.

**Comment by tog22** [comment]
Yep, this has been in the queue to fix for ages but we haven't had capacity until recently. Someone just finished transferring the 2013 data into the new 'Selected past donations' table (which lets you specify when they were made), so I've deleted those old fields. I've backed up the 2013 income data (note to self: currently to my computer at `Documents/Projects/EA\ Hub/backups/old\ data`) and deleted income from the site altogether. I deleted it partly because on reflection it may be less natural to share, partly because it's particularly likely to look oddly out of date, etc.
